### ISSUE TITLE
Define camera-model specific settings

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/aind-data-schema#513]
**Is your feature request related to a problem? Please describe.**
How should users specify camera-specific properties? Some cameras allow the specification of additional properties, such as exposure, gain, on-chip algorithm processing modes, trigger-mode, etc... It is currently not clear how to write this in the current specs.

https://github.com/AllenNeuralDynamics/aind-data-schema/blob/773ee35126cb91689a0254d9d561b55f04093233/src/aind_data_schema/device.py#L309

**Describe the solution you'd like**

Subclassing the Camera with additional properties might do the trick. In my case, i would want to have access to the following (some might already exist?):
```json
"spinnakerCamera": {
      "properties": {
        "binning": {
          "default": 1,
          "minimum": 1,
          "type": "integer"
        },
        "colorProcessing": {
          "default": "Default",
          "enum": [
            "Default",
            "NoColorProcessing"
          ],
          "type": "string"
        },
        "exposure": {
          "default": 1000,
          "minimum": 1,
          "type": "integer"
        },
        "frameRate": {
          "default": 30,
          "maximum": 350,
          "minimum": 1,
          "type": "integer"
        },
        "gain": {
          "default": 0,
          "minimum": 0,
          "type": "number"
        },
        "serialNumber": {
          "type": "string"
        }
      },
      "required": [
        "serialNumber"
      ],
      "type": "object"
    },
```
**Describe alternatives you've considered**
Pass arguments as additional properties?

**Comment by saskiad** [comment]
I'm not sure it makes sense to add specs in the metadata. Having model number of manufacturer means that we can find the specs of the camera. What we want is the actual settings of these parameters that is used - not what it could possibly be.

The things here that I don't think we currently have are exposure and gain. What are the units for these? (Binning is being added in a separate issue).

**Comment by bruno-f-cruz** [comment]
To clarify, all the specs I listed above that are settings that we use and set on every single session, they do not reflect what is possible but what we actually instantiate of a given experiment. So I would argue they all fall within your definition of metadata, no? 

At the same time I agree it doesn't seem sustainable to add all the properties of all possible camera model.

Binning is unitless
Exposure, for this camera, is in nanoseconds, but it varies from manufacturer to manufacturer.

**Comment by saskiad** [comment]
@bruno-f-cruz is this solved with the detector/camera class? Or are there still things missing?

**Comment by bruno-f-cruz** [comment]
There are still missing settings that we might or might not use. I think this would be better address by considering #708. Otherwise, I can try to come up with the list of settings we might want to use. Right now is about 15 or so.

**Comment by jtyoung84** [comment]
Closed by closing #708
